version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    networks:
      - hk-network
    ports:
      - '27017:27017'
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - hk-network
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
#      ME_CONFIG_MONGODB_URL: mongodb://admin:pass@mongo:27017/
#      ME_CONFIG_BASICAUTH: false

networks:
  hk-network:
    driver: "bridge"