name: Deploy App on EC2
on:
  pull_request:
    branches:
      ['main', 'master']

jobs:
  copy:
    name: Update files in EC2
    runs-on: ubuntu-latest
    steps:
      - name: checkout the files
        uses: actions/checkout@v3

      - name: copy files
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
          SOURCE: "./"
          REMOTE_HOST: "ec2-3-88-235-105.compute-1.amazonaws.com"
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user"
          EXCLUDE: ".git"

#  database:
#    needs: copy
#    runs-on: self-hosted
#    steps:
#      - name: Initialize database
#        run: docker compose up

  deploy:
    #needs: database
    runs-on: self-hosted
    steps:
      - name: Build app image
        run: docker build -t bookstore .
      - name: Run build
        run: docker run -p 8080:8080 --network=bookstore_hk-network bookstore

