name: Deploy App on EC2
on:
  pull_request:
    branches:
      ['main', 'master']

jobs:
  build:
    name: build and upload docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: generate image
        run: docker build . -t isaquegarcia1/bookstore:zero-touch

      - name: login into docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASS}}

      - name: docker push image
        run: docker push isaquegarcia1/bookstore:zero-touch

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pull docker image
        run: docker pull isaquegarcia1/bookstore:zero-touch

      - name: remove container
        run: docker rm -f container_bookstore

      - name: Download and run app
        run: docker run -p 8080:8080 --network=ec2-user_hk-network --name container_bookstore isaquegarcia1/bookstore:zero-touch -d

